### ISSUE TITLE
O controle de sessão não está funcionando para adm

### ISSUE THREAD

**Issue by aceiro** [aceiro/eventosasser#21]
Ao enviar um resumo com outro usuário a tela de adm não filtra e está abrindo o controle de professor @cecanho você tem consegue corrigir isso ?

**Comment by cecanho** [comment]
Oi Erik, vou ver isso agora.

Em 11 de maio de 2016 16:48, Erik Aceiro Antonio <notifications@github.com>
escreveu:

> Ao enviar um resumo com outro usuário a tela de adm não filtra e está
> abrindo o controle de professor @cecanho <https://github.com/cecanho>
> você tem consegue corrigir isso ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/aceiro/eventosasser/issues/21>
>



-- 
Cristiano José Cecanho

cecanho@gmail.com
http://cecanho.com.br

**Comment by aceiro** [comment]
Oi @cecanho 

Parece que foi feito o merge com essas alterações, o ideal seria termos um branch de hotfix para corrigir os problemas e depois de validado, mergear para a master.

**Comment by aceiro** [comment]
@cecanho 

Vamos validar antes de fazer o merge, ok ?
